FROM postgres:15.1
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD 1234

COPY ./replica_data /var/lib/postgresql/data


# CMD ["/bin/bash", "setup.sh"]
#ENTRYPOINT ["/bin/bash", "server_config/setup.sh"]

