version: '2'
services:

  ## Config Servers
  config01:
    container_name: config01
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver  --oplogSize 16
    volumes:
      - ./scripts:/scripts

  config02:
    container_name: config02
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver  --oplogSize 16
    volumes:
      - ./scripts:/scripts
  
  config03:
    container_name: config03
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver  --oplogSize 16
    volumes:
      - ./scripts:/scripts


  ## Shards
  shard01a:
    container_name: shard01a
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01  --oplogSize 16
    volumes:
      - ./scripts:/scripts

  shard01b:
    container_name: shard01b
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard01  --oplogSize 16
    volumes:
      - ./scripts:/scripts

  shard02a:
    container_name: shard02a
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02  --oplogSize 16
    volumes:
      - ./scripts:/scripts

  shard02b:
    container_name: shard02b
    image: mongo
    command: mongod --port 27019 --shardsvr --replSet shard02  --oplogSize 16
    volumes:
      - ./scripts:/scripts

  shard03a:
    container_name: shard03a
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet shard03  --oplogSize 16
    volumes:
      - ./scripts:/scripts

  shard03b:
    container_name: shard03b
    image: mongo
    command: mongod --port 27020 --shardsvr --replSet shard03  --oplogSize 16
    volumes:
      - ./scripts:/scripts

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config01:27017,config02:27017,config03:27017 --bind_ip_all
    ports:
      - "27016:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard02a
      - shard02b
      - shard03a
      - shard03b
