version: '3'

# sudo rm -rf ./master/data/*
# sudo rm -rf ./slave/data/*


services:
  mysql_master:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    #env_file:
    #  - ./master/mysql_master.env
    container_name: "mysql_master"
    restart: always
    ports:
      - 4406:3306
    volumes:
      - ./master/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./master/data:/var/lib/mysql
    networks:
      - overlay

  mysql_slave:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    #env_file:
    #  - ./slave/mysql_slave.env
    container_name: "mysql_slave"
    restart: always
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./slave/data:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay:

