version: '3.3'

# mysql -u root -h 0.0.0.0 -p
# mysql -u root -h 0.0.0.0 -p
# pw: 1234

# docker exec -it mysql_replica_db_1 bash
# mysql -u root -h 0.0.0.0 -p

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      #MYSQL_ROOT_PASSWORD: '12345'
      #MYSQL_ALLOW_EMPTY_PASSWORD: ''
      #MYSQL_RANDOM_ROOT_PASSWORD: ''
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      
# Names our volume
volumes:
  my-db:
