version: '3.8'
services:
  node1:
    image: 'cassandra:latest'
    container_name: node_1
    ports:
      - '9042:9042'
      - '9160:9160'
    environment:
      CASSANDRA_CLUSTER_NAME: cluster_1
      CASSANDRA_SEEDS: 'node1,node2,node3'
    restart: unless-stopped
  node2:
    image: 'cassandra:latest'
    container_name: node_2
    environment:
      CASSANDRA_CLUSTER_NAME: cluster_1
      CASSANDRA_SEEDS: 'node1,node2,node3'
    restart: unless-stopped
  node3:
    image: 'cassandra:latest'
    container_name: node_3
    environment:
      CASSANDRA_CLUSTER_NAME: cluster_1
      CASSANDRA_SEEDS: 'node1,node2,node3'
    restart: unless-stopped

