version: '3.8'


services:

  # Datacenter 1 
  node1:
    image: 'cassandra:latest'
    container_name: node_1
    ports:
      - '9042:9042'
      - '9160:9160'
    environment:
      CASSANDRA_CLUSTER_NAME: cluster_1
      CASSANDRA_SEEDS: 'node1'
      DATACENTER: DC1
    restart: unless-stopped
    
  node2:
    image: 'cassandra:latest'
    container_name: node_2
    environment:
      CASSANDRA_CLUSTER_NAME: cluster_1
      CASSANDRA_SEEDS: 'node1'
      DATACENTER: DC1
    restart: unless-stopped
    
  # Datacenter 2  
  node3:
    image: 'cassandra:latest'
    container_name: node_3
    ports:
      - '9043:9042'
      - '9161:9160'
    environment:
      CASSANDRA_CLUSTER_NAME: cluster_1
      CASSANDRA_SEEDS: 'node1'
      DATACENTER: DC2
    restart: unless-stopped

  node4:
    image: 'cassandra:latest'
    container_name: node_4
    environment:
      CASSANDRA_CLUSTER_NAME: cluster_1
      CASSANDRA_SEEDS: 'node1'
      DATACENTER: DC2
    restart: unless-stopped
    
